builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  -
    name: birdwatcher
    folder: Formula
    homepage: "https://github.com/zilliztech/milvus-backup"
    repository:
      owner: zilliztech
      name: homebrew-tap
      token: "{{ .Env.GITHUB_HOMEBREW_TOKEN }}"

release:
  draft: true
  mode: append
  extra_files:
    - glob: ./birdwatcher-build/**/*.tar.gz
    - glob: ./birdwatcher-build/checksums.txt
  name_template: "Release {{.Tag}}"
  header: |
    # What's Changed
    ## 🚀 Features
    ## 🎄 Enhancements
    ## 🐛 Bug Fixes